Pagopa 1147 amex filter
pagopa/pagopa-afm-calculator pull request #99
Opened 2023-08-08 10:05 UTC by alessio-acitelli

#### List of Changes

- added management for AMEX payments

#### Motivation and Context

- new business request

#### How Has This Been Tested?

Junit and manual test

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-08-08 13:52 UTC, alessio-acitelli commented
update_code

2023-08-21 14:59 UTC, pasqualespica requested changes
ok, but remove key

2023-08-21 14:59 UTC, pasqualespica commented on src/main/resources/application-dev.properties
> +azure.storage.connection=DefaultEndpointsProtocol=https;AccountName=pagopadweuafmsa;AccountKey=RRDygFmNKKHpX+icQN4F3UdNzaoCgbbS4K8QDjFq0vJUCUKPpBv2DykLYm22OlqsIbZCPYNQJdEO+AStoX9jzw==;EndpointSuffix=
remove it

2023-08-22 13:47 UTC, alessio-acitelli commented on src/main/resources/application-dev.properties
> +azure.storage.connection=DefaultEndpointsProtocol=https;AccountName=pagopadweuafmsa;AccountKey=RRDygFmNKKHpX+icQN4F3UdNzaoCgbbS4K8QDjFq0vJUCUKPpBv2DykLYm22OlqsIbZCPYNQJdEO+AStoX9jzw==;EndpointSuffix=
done

2023-08-22 13:47 UTC, alessio-acitelli commented on src/main/resources/application-dev.properties
> +azure.storage.connection=DefaultEndpointsProtocol=https;AccountName=pagopadweuafmsa;AccountKey=RRDygFmNKKHpX+icQN4F3UdNzaoCgbbS4K8QDjFq0vJUCUKPpBv2DykLYm22OlqsIbZCPYNQJdEO+AStoX9jzw==;EndpointSuffix=
done

2023-08-22 14:39 UTC, merged